In [1]:
import numpy as np
rng = np.random.RandomState(1)
X = rng.randint(5, size=(6, 10))
Y = np.array([1, 2, 3, 4, 4, 5])
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(X, Y)
BernoulliNB()
print(clf.predict(X[2:3]))

[3]


In [19]:
print(X)
print("*"*100)
print(X[2:3])

[[3 4 0 1 3 0 0 1 4 4]
 [1 2 4 2 4 3 4 2 4 2]
 [4 1 1 0 1 1 1 1 0 4]
 [1 0 0 3 2 1 0 3 1 1]
 [3 4 0 1 3 4 2 4 0 3]
 [1 2 0 4 1 2 2 1 0 1]]
****************************************************************************************************
[[4 1 1 0 1 1 1 1 0 4]]


In [7]:
import numpy as np
rng = np.random.RandomState(1)
X = rng.randint(5, size=(6, 10))
print(X)
print("*"*100)
print(X[2:3])
print(X[:,2:4])

[[3 4 0 1 3 0 0 1 4 4]
 [1 2 4 2 4 3 4 2 4 2]
 [4 1 1 0 1 1 1 1 0 4]
 [1 0 0 3 2 1 0 3 1 1]
 [3 4 0 1 3 4 2 4 0 3]
 [1 2 0 4 1 2 2 1 0 1]]
****************************************************************************************************
[[4 1 1 0 1 1 1 1 0 4]]
[[0 1]
 [4 2]
 [1 0]
 [0 3]
 [0 1]
 [0 4]]
